PRESETS = [
    {
        "id": "no-lies",
        "name": "Nobody Can Lie",
        "rules": "Lying is physically impossible. Every person can only speak what they believe to be true. Emotions are visible on everyone's face and cannot be hidden.",
        "teaser": "They invented silence clubs by month 3.",
        "population": 25,
        "duration_days": 365,
    },
    {
        "id": "full-communism",
        "name": "Full Communism",
        "rules": "No private property exists. All resources are communal. No one can own more than they need. A community council allocates resources based on need.",
        "teaser": "It worked. Then it didn't.",
        "population": 25,
        "duration_days": 365,
    },
    {
        "id": "direct-democracy",
        "name": "Direct Democracy",
        "rules": "Every decision that affects more than one person must be voted on by the entire community. No representatives, no delegation. Every citizen has equal vote.",
        "teaser": "They voted 47 times on day 1. By day 30, nobody showed up.",
        "population": 25,
        "duration_days": 365,
    },
    {
        "id": "no-digital",
        "name": "No Phones, No Internet",
        "rules": "All communication is face-to-face only. No long-distance messaging, no written notes left behind, no technology for communication. You must be physically present to interact.",
        "teaser": "Rumors moved slower but hit harder.",
        "population": 25,
        "duration_days": 365,
    },
    {
        "id": "meritocracy",
        "name": "Absolute Meritocracy",
        "rules": "Social status, housing, food quality, and privileges are strictly determined by measurable productive output. Nothing else matters — not age, relationships, or character.",
        "teaser": "The artists starved. Then they revolted.",
        "population": 25,
        "duration_days": 365,
    },
    {
        "id": "anonymity",
        "name": "Total Anonymity",
        "rules": "No one has a persistent name or identity. Every day, physical appearances change randomly. You cannot recognize anyone. Reputation does not exist.",
        "teaser": "Trust became the scarcest resource.",
        "population": 25,
        "duration_days": 365,
    },
    {
        "id": "tesla-rebrand",
        "name": "Tesla Logo Change",
        "rules": "Tesla is a premium electric vehicle brand known for innovation, minimalism, and futuristic identity. The customer base includes tech enthusiasts, luxury buyers, environmentalists, and mainstream adopters. Brand identity is deeply tied to Elon Musk's personal brand. Tesla announces a playful new logo to appeal to mainstream buyers.",
        "teaser": "The subreddit burned for 72 hours. Then something unexpected happened.",
        "population": 20,
        "duration_days": 90,
        "proposed_change": "Tesla changes its iconic T logo to a more playful, rounded, consumer-friendly logo intended to appeal to a broader mass-market audience.",
        "segments": [
            {"name": "Brand loyalists", "description": "Current Tesla owners who see ownership as identity. They bought Tesla partly as a status symbol and feel personally attached to the brand aesthetic.", "count": 5},
            {"name": "Tech enthusiasts", "description": "Love Tesla for the technology — autopilot, OTA updates, battery innovation. Less attached to the logo, more to the engineering.", "count": 4},
            {"name": "Luxury buyers", "description": "Came from BMW/Mercedes. Chose Tesla for the premium feel. Care deeply about brand image and how the car reflects on them.", "count": 3},
            {"name": "First-time buyers", "description": "Considering Tesla for the first time. Comparing with Rivian, Lucid, and traditional EVs. Price and perception matter most.", "count": 4},
            {"name": "Skeptics", "description": "Don't trust Tesla or Musk. Watching from the sidelines. Would need a strong reason to buy.", "count": 2},
            {"name": "Casual observers", "description": "General public, vaguely aware of Tesla. Not currently in-market but influenced by what they see others doing.", "count": 2},
        ],
    },
    {
        "id": "netflix-price-hike",
        "name": "Netflix Price Hike",
        "rules": "Netflix dominates streaming with 200M+ subscribers. Competitors include Disney+, HBO Max, and Apple TV+. Customers are price-sensitive but habit-driven. Content library is the main differentiator. Account sharing has been a gray area.",
        "teaser": "They all said they'd cancel. Most didn't. But the ones who did...",
        "population": 20,
        "duration_days": 90,
        "proposed_change": "Netflix raises prices by 40% while adding ads to the basic tier and cracking down on password sharing.",
        "segments": [
            {"name": "Binge watchers", "description": "Heavy users who watch daily. Netflix is their primary entertainment. Would feel lost without it.", "count": 5},
            {"name": "Budget subscribers", "description": "On the cheapest plan. Share passwords. Extremely price-sensitive. Will cancel if value drops.", "count": 5},
            {"name": "Multi-platform users", "description": "Subscribe to 3+ services. Netflix is one of many. Quick to drop the weakest link.", "count": 4},
            {"name": "Loyal premium users", "description": "Pay for 4K, have family plans. Been subscribers for 5+ years. Habit-driven loyalty.", "count": 3},
            {"name": "Casual watchers", "description": "Watch a few shows a month. Often forget they have Netflix. Low engagement, low switching cost.", "count": 3},
        ],
    },
    {
        "id": "apple-port-removal",
        "name": "Apple Removes the Port",
        "rules": "Apple is known for courage moves: removing the headphone jack, the home button, now the last physical port. Pro users depend on wired connections for reliability. Casual users barely use the port. The ecosystem is deeply locked in.",
        "teaser": "The pros raged. The casuals shrugged. Then the pros bought it anyway.",
        "population": 20,
        "duration_days": 90,
        "proposed_change": "Apple removes the last physical port from the iPhone. Everything is wireless — charging, data transfer, accessories.",
        "segments": [
            {"name": "Pro users", "description": "Developers, photographers, creators. Depend on wired connections for reliability and speed. Vocal and influential.", "count": 5},
            {"name": "Apple loyalists", "description": "Own everything Apple. AirPods, MacBook, Apple Watch. Will buy whatever Apple makes.", "count": 4},
            {"name": "Casual iPhone users", "description": "Use iPhone for calls, texts, social media. Rarely plug anything in. Don't care about ports.", "count": 5},
            {"name": "Android considerers", "description": "Currently on iPhone but not locked in. Open to switching if Apple pushes too far.", "count": 3},
            {"name": "Tech commentators", "description": "Influencers and tech reviewers. Shape public opinion. Care about being contrarian and generating engagement.", "count": 3},
        ],
    },
    {
        "id": "new-competitor",
        "name": "New Competitor Enters",
        "rules": "A mature market with an established leader charging premium prices. Customer satisfaction is high but not universal. Switching costs exist but aren't insurmountable. The leader has brand loyalty but also complacency.",
        "teaser": "Good enough is the most dangerous phrase in business.",
        "population": 20,
        "duration_days": 90,
        "proposed_change": "A well-funded startup launches a product that's 30% cheaper with 80% of the features of the market leader.",
        "segments": [
            {"name": "Loyal customers", "description": "Long-time users of the incumbent. Satisfied with the product. High switching costs mentally.", "count": 5},
            {"name": "Price-sensitive users", "description": "Use the incumbent but always looking for a deal. Would switch for significant savings.", "count": 5},
            {"name": "Power users", "description": "Need all the features. The 20% missing from the startup matters to them.", "count": 3},
            {"name": "New entrants", "description": "Just entering the market. No loyalty to anyone. Comparing options fresh.", "count": 4},
            {"name": "Churned customers", "description": "Left the incumbent previously. Open to the startup as an alternative.", "count": 3},
        ],
    },
    {
        "id": "brand-crisis",
        "name": "CEO Scandal",
        "rules": "A beloved consumer brand whose CEO is a public figure and brand ambassador. The product hasn't changed. Customer loyalty is split between loving the product and admiring the founder. Social media amplifies everything.",
        "teaser": "They loved the brand. They hated the founder. They couldn't separate the two.",
        "population": 20,
        "duration_days": 90,
        "proposed_change": "The CEO is caught in a major scandal. The product quality remains identical, but the person behind the brand is now controversial.",
        "segments": [
            {"name": "Product-first fans", "description": "Love the product for what it does. Don't care about the CEO. Separate the art from the artist.", "count": 5},
            {"name": "Founder fans", "description": "Bought the product partly because of the founder's vision and personality. Feel personally betrayed.", "count": 4},
            {"name": "Values-driven consumers", "description": "Care deeply about ethics. Will boycott brands that don't align with their values regardless of product quality.", "count": 4},
            {"name": "Pragmatists", "description": "Just want the product to work. Don't follow brand drama. Will only leave if the product declines.", "count": 4},
            {"name": "Social media amplifiers", "description": "Influencers and commentators. Will make the scandal louder. Care about engagement more than the product.", "count": 3},
        ],
    },
]
